version: '3'

services:
  postgres:
    image: postgres:14-alpine
    container_name: challengedb
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: challengedb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    container_name: backend-rest
    build:
      context: ./backend/
      dockerfile: Dockerfile
    image: backend-rest
    environment:
      - TOKEN_THE_MOVIE_DB=${TOKEN_THE_MOVIE_DB}
    ports:
      - "4001:4001"
    depends_on:
      - postgres
    restart: always
  ui:
    container_name: ui
    build:
      context: ./ui/
      dockerfile: Dockerfile
    image: ui
    ports:
      - "8080:4300"
      - "80:4300"
    restart: always

volumes:
  pgdata: