version: '3'
      
services:
  postgres:
    image: postgres:14-alpine
    container_name: challengedb
    network_mode: host
    environment:
      POSTGRES_DB: challengedb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    container_name: backend-rest
    build:
      context: ./backend/
      dockerfile: Dockerfile
    image: backend-rest
    network_mode: host
    environment:
      - TOKEN_THE_MOVIE_DB=${TOKEN_THE_MOVIE_DB}
    depends_on:
      - postgres
    restart: always
  ui:
    container_name: ui
    build:
      context: ./ui/
      dockerfile: Dockerfile
    image: ui
    network_mode: host
    restart: always
volumes:
  pgdata: